In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn import metrics
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split 
from sklearn.tree import DecisionTreeClassifier 

In [35]:
df = pd.read_excel('reaction_time_cleaned.xlsx')
df = df[np.abs(df.time - df.time.mean()) <= (3*df.time.std())]
df.shape

(299, 9)

In [36]:
x = df.drop(columns = 'method')
y = df['method']

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [38]:
X_train.shape, X_test.shape

((209, 8), (90, 8))

In [39]:
y_train.shape, y_test.shape

((209,), (90,))

In [40]:
import category_encoders as ce
# import category encoders 

In [41]:
# encode remaining variables with one-hot encoding 
 
encoder = ce.OneHotEncoder() 
 
X_train = encoder.fit_transform(X_train) 
X_test = encoder.transform(X_test) 
X_train.shape

C:\ProgramData\Anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


(209, 21)

In [42]:
X_train.head()

sex_1  sex_2  gender_1  gender_2  ethnicity_1  ethnicity_2  ethnicity_3  \
287      1      0         1         0            1            0            0   
46       0      1         0         1            0            1            0   
246      0      1         0         1            0            0            1   
194      1      0         1         0            0            0            0   
157      0      1         0         1            1            0            0   

     ethnicity_4  age_1  age_2  ...  age_4  age_5  tech_level  user_id  \
287            0      1      0  ...      0      0           5     1005   
46             0      1      0  ...      0      0          10     9360   
246            0      0      1  ...      0      0          10     4973   
194            1      0      0  ...      0      0          10     6948   
157            0      0      1  ...      0      0           8     1002   

     round_1  round_2  round_3  round_4  round_5      time  
287        1        0        0        0        0  0.257000  
46         0        1        0        0        0  0.295999  
246        1        0        0        0        0  0.298999  
194        0        0        1        0        0  0.328999  
157        0        0        0        1        0  0.324900  

[5 rows x 21 columns]

In [43]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB()

In [44]:
y_pred_class = nb.predict(X_test)
y_pred_class.shape

(90,)

In [45]:
from sklearn.metrics import accuracy_score

print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_class)))

Model accuracy score: 0.2556


In [46]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(nb.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(nb.score(X_test, y_test)))

Training set score: 0.3732
Test set score: 0.2556


In [47]:
print("The classification report is as follows...\n")
print(classification_report(y_pred_class,y_test))

The classification report is as follows...

              precision    recall  f1-score   support

       Mouse       0.18      0.25      0.21        24
    Spacebar       0.23      0.35      0.28        23
 Touchscreen       0.41      0.21      0.28        43

    accuracy                           0.26        90
   macro avg       0.27      0.27      0.25        90
weighted avg       0.30      0.26      0.26        90



In [48]:
#Let's test the confusion matrix!

cm = confusion_matrix(y_test, y_pred_class)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[ 6  9 18]
 [11  8 16]
 [ 7  6  9]]

True Positives(TP) =  6

True Negatives(TN) =  8

False Positives(FP) =  9

False Negatives(FN) =  11


In [50]:
# Compute predicted probabilities: y_pred_prob
y_pred_prob = nb.predict_proba(X_test)[:,1]
metrics.roc_auc_score(y_test, y_pred_prob)

ValueError: multi_class must be in ('ovo', 'ovr')

In [51]:
from sklearn.metrics import precision_recall_curve 

precision, recall, thresholds = precision_recall_curve(y_test, y_pred_prob)
# create plot
plt.plot(precision, recall, label='Precision-recall curve')
plt.xlabel('Precision')
plt.ylabel('Recall')
plt.title('Precision-recall curve')
plt.legend(loc="lower left")


ValueError: multiclass format is not supported